package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "services")
public class Account implements java.io.Serializable {

	private Long accountId;
	private String accoountType;
	private String accountDetails;
	private String accountName;
	private Date closeDate;
	private String isActive;
	private Date openDate;
	private Set<Expense> expenses = new HashSet<Expense>(0);
	private Set<Collection> collections = new HashSet<Collection>(0);

	public Account() {
	}

	public Account(String accoountType, String accountDetails,
			String accountName, Date closeDate, String isActive, Date openDate,
			Set<Expense> expenses, Set<Collection> collections) {
		this.accoountType = accoountType;
		this.accountDetails = accountDetails;
		this.accountName = accountName;
		this.closeDate = closeDate;
		this.isActive = isActive;
		this.openDate = openDate;
		this.expenses = expenses;
		this.collections = collections;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "account_id", unique = true, nullable = false)
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "accoount_type", length = 100)
	public String getAccoountType() {
		return this.accoountType;
	}

	public void setAccoountType(String accoountType) {
		this.accoountType = accoountType;
	}

	@Column(name = "account_details")
	public String getAccountDetails() {
		return this.accountDetails;
	}

	public void setAccountDetails(String accountDetails) {
		this.accountDetails = accountDetails;
	}

	@Column(name = "account_name")
	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "close_date", length = 10)
	public Date getCloseDate() {
		return this.closeDate;
	}

	public void setCloseDate(Date closeDate) {
		this.closeDate = closeDate;
	}

	@Column(name = "is_active", length = 1)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "open_date", length = 10)
	public Date getOpenDate() {
		return this.openDate;
	}

	public void setOpenDate(Date openDate) {
		this.openDate = openDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Expense> getExpenses() {
		return this.expenses;
	}

	public void setExpenses(Set<Expense> expenses) {
		this.expenses = expenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Collection> getCollections() {
		return this.collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

}
