package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actions generated by hbm2java
 */
@Entity
@Table(name = "actions", catalog = "services")
public class Actions implements java.io.Serializable {

	private Integer actionId;
	private String name;
	private String displayTitle;
	private String displayText;
	private String language;
	private String type;
	private Integer followUpActionId;
	private String url;
	private String active;
	private String triggerTiming;
	private String triggerDistance;
	private String triggerCondition;
	private String eventId;
	private String behavior;
	private String parameter;
	private String os;
	private Date effectiveDate;
	private Date expiredDate;
	private Date createDate;

	public Actions() {
	}

	public Actions(String name, String displayTitle, String displayText,
			String type, String active, String triggerTiming,
			String triggerDistance, String triggerCondition, Date createDate) {
		this.name = name;
		this.displayTitle = displayTitle;
		this.displayText = displayText;
		this.type = type;
		this.active = active;
		this.triggerTiming = triggerTiming;
		this.triggerDistance = triggerDistance;
		this.triggerCondition = triggerCondition;
		this.createDate = createDate;
	}

	public Actions(String name, String displayTitle, String displayText,
			String language, String type, Integer followUpActionId, String url,
			String active, String triggerTiming, String triggerDistance,
			String triggerCondition, String eventId, String behavior,
			String parameter, String os, Date effectiveDate, Date expiredDate,
			Date createDate) {
		this.name = name;
		this.displayTitle = displayTitle;
		this.displayText = displayText;
		this.language = language;
		this.type = type;
		this.followUpActionId = followUpActionId;
		this.url = url;
		this.active = active;
		this.triggerTiming = triggerTiming;
		this.triggerDistance = triggerDistance;
		this.triggerCondition = triggerCondition;
		this.eventId = eventId;
		this.behavior = behavior;
		this.parameter = parameter;
		this.os = os;
		this.effectiveDate = effectiveDate;
		this.expiredDate = expiredDate;
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "actionID", unique = true, nullable = false)
	public Integer getActionId() {
		return this.actionId;
	}

	public void setActionId(Integer actionId) {
		this.actionId = actionId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "displayTitle", nullable = false)
	public String getDisplayTitle() {
		return this.displayTitle;
	}

	public void setDisplayTitle(String displayTitle) {
		this.displayTitle = displayTitle;
	}

	@Column(name = "displayText", nullable = false, length = 65535)
	public String getDisplayText() {
		return this.displayText;
	}

	public void setDisplayText(String displayText) {
		this.displayText = displayText;
	}

	@Column(name = "language")
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "type", nullable = false, length = 50)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "followUpActionID")
	public Integer getFollowUpActionId() {
		return this.followUpActionId;
	}

	public void setFollowUpActionId(Integer followUpActionId) {
		this.followUpActionId = followUpActionId;
	}

	@Column(name = "url", length = 65535)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "active", nullable = false)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "triggerTiming", nullable = false)
	public String getTriggerTiming() {
		return this.triggerTiming;
	}

	public void setTriggerTiming(String triggerTiming) {
		this.triggerTiming = triggerTiming;
	}

	@Column(name = "triggerDistance", nullable = false)
	public String getTriggerDistance() {
		return this.triggerDistance;
	}

	public void setTriggerDistance(String triggerDistance) {
		this.triggerDistance = triggerDistance;
	}

	@Column(name = "triggerCondition", nullable = false)
	public String getTriggerCondition() {
		return this.triggerCondition;
	}

	public void setTriggerCondition(String triggerCondition) {
		this.triggerCondition = triggerCondition;
	}

	@Column(name = "eventID")
	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	@Column(name = "behavior")
	public String getBehavior() {
		return this.behavior;
	}

	public void setBehavior(String behavior) {
		this.behavior = behavior;
	}

	@Column(name = "parameter", length = 65535)
	public String getParameter() {
		return this.parameter;
	}

	public void setParameter(String parameter) {
		this.parameter = parameter;
	}

	@Column(name = "os")
	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "effectiveDate", length = 19)
	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiredDate", length = 19)
	public Date getExpiredDate() {
		return this.expiredDate;
	}

	public void setExpiredDate(Date expiredDate) {
		this.expiredDate = expiredDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
