package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemberDetails generated by hbm2java
 */
@Entity
@Table(name = "member_details", catalog = "services")
public class MemberDetails implements java.io.Serializable {

	private Long id;
	private Owner owner;
	private byte[] bloodGroup;
	private Date createDate;
	private Date dateOfBirth;
	private String email;
	private String gender;
	private String hobby;
	private Float income;
	private String location;
	private String mobileNo;
	private String motherTongue;
	private String name;
	private String nationality;
	private String occupation;
	private String organizaton;
	private String other;
	private Long parentId;
	private String relation;

	public MemberDetails() {
	}

	public MemberDetails(Date createDate) {
		this.createDate = createDate;
	}

	public MemberDetails(Owner owner, byte[] bloodGroup, Date createDate,
			Date dateOfBirth, String email, String gender, String hobby,
			Float income, String location, String mobileNo,
			String motherTongue, String name, String nationality,
			String occupation, String organizaton, String other, Long parentId,
			String relation) {
		this.owner = owner;
		this.bloodGroup = bloodGroup;
		this.createDate = createDate;
		this.dateOfBirth = dateOfBirth;
		this.email = email;
		this.gender = gender;
		this.hobby = hobby;
		this.income = income;
		this.location = location;
		this.mobileNo = mobileNo;
		this.motherTongue = motherTongue;
		this.name = name;
		this.nationality = nationality;
		this.occupation = occupation;
		this.organizaton = organizaton;
		this.other = other;
		this.parentId = parentId;
		this.relation = relation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id")
	public Owner getOwner() {
		return this.owner;
	}

	public void setOwner(Owner owner) {
		this.owner = owner;
	}

	@Column(name = "blood_group")
	public byte[] getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(byte[] bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_of_birth", length = 10)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "gender", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "hobby")
	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	@Column(name = "income", precision = 12, scale = 0)
	public Float getIncome() {
		return this.income;
	}

	public void setIncome(Float income) {
		this.income = income;
	}

	@Column(name = "location", length = 100)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "mobile_no", length = 14)
	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "mother_tongue", length = 100)
	public String getMotherTongue() {
		return this.motherTongue;
	}

	public void setMotherTongue(String motherTongue) {
		this.motherTongue = motherTongue;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "nationality", length = 100)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "occupation", length = 100)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "organizaton", length = 100)
	public String getOrganizaton() {
		return this.organizaton;
	}

	public void setOrganizaton(String organizaton) {
		this.organizaton = organizaton;
	}

	@Column(name = "other")
	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	@Column(name = "parent_id")
	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	@Column(name = "relation", length = 100)
	public String getRelation() {
		return this.relation;
	}

	public void setRelation(String relation) {
		this.relation = relation;
	}

}
