package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Owner generated by hbm2java
 */
@Entity
@Table(name = "owner", catalog = "services")
public class Owner implements java.io.Serializable {

	private Long id;
	private String active;
	private Date createdate;
	private String doorno;
	private Integer floor;
	private Long imageId;
	private String isOwner;
	private String mobile;
	private String name;
	private String pid;
	private String rrno;
	private Set<Collection> collections = new HashSet<Collection>(0);
	private Set<MemberDetails> memberDetailses = new HashSet<MemberDetails>(0);

	public Owner() {
	}

	public Owner(Date createdate, String name) {
		this.createdate = createdate;
		this.name = name;
	}

	public Owner(String active, Date createdate, String doorno, Integer floor,
			Long imageId, String isOwner, String mobile, String name,
			String pid, String rrno, Set<Collection> collections,
			Set<MemberDetails> memberDetailses) {
		this.active = active;
		this.createdate = createdate;
		this.doorno = doorno;
		this.floor = floor;
		this.imageId = imageId;
		this.isOwner = isOwner;
		this.mobile = mobile;
		this.name = name;
		this.pid = pid;
		this.rrno = rrno;
		this.collections = collections;
		this.memberDetailses = memberDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "active", length = 1)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createdate", nullable = false, length = 19)
	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	@Column(name = "doorno", length = 50)
	public String getDoorno() {
		return this.doorno;
	}

	public void setDoorno(String doorno) {
		this.doorno = doorno;
	}

	@Column(name = "floor")
	public Integer getFloor() {
		return this.floor;
	}

	public void setFloor(Integer floor) {
		this.floor = floor;
	}

	@Column(name = "image_id")
	public Long getImageId() {
		return this.imageId;
	}

	public void setImageId(Long imageId) {
		this.imageId = imageId;
	}

	@Column(name = "is_owner", length = 1)
	public String getIsOwner() {
		return this.isOwner;
	}

	public void setIsOwner(String isOwner) {
		this.isOwner = isOwner;
	}

	@Column(name = "mobile", length = 100)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "pid", length = 10)
	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	@Column(name = "rrno", length = 15)
	public String getRrno() {
		return this.rrno;
	}

	public void setRrno(String rrno) {
		this.rrno = rrno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "owner")
	public Set<Collection> getCollections() {
		return this.collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "owner")
	public Set<MemberDetails> getMemberDetailses() {
		return this.memberDetailses;
	}

	public void setMemberDetailses(Set<MemberDetails> memberDetailses) {
		this.memberDetailses = memberDetailses;
	}

}
