package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Postalcode generated by hbm2java
 */
@Entity
@Table(name = "postalcode", catalog = "services")
public class Postalcode implements java.io.Serializable {

	private Integer id;
	private String officename;
	private String pincode;
	private String officeType;
	private String deliverystatus;
	private String divisionname;
	private String regionname;
	private String circlename;
	private String taluk;
	private String districtname;
	private String statename;

	public Postalcode() {
	}

	public Postalcode(String officename, String pincode, String officeType,
			String deliverystatus, String divisionname, String regionname,
			String circlename, String taluk, String districtname,
			String statename) {
		this.officename = officename;
		this.pincode = pincode;
		this.officeType = officeType;
		this.deliverystatus = deliverystatus;
		this.divisionname = divisionname;
		this.regionname = regionname;
		this.circlename = circlename;
		this.taluk = taluk;
		this.districtname = districtname;
		this.statename = statename;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "officename", length = 225)
	public String getOfficename() {
		return this.officename;
	}

	public void setOfficename(String officename) {
		this.officename = officename;
	}

	@Column(name = "pincode", length = 10)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "officeType", length = 225)
	public String getOfficeType() {
		return this.officeType;
	}

	public void setOfficeType(String officeType) {
		this.officeType = officeType;
	}

	@Column(name = "deliverystatus", length = 225)
	public String getDeliverystatus() {
		return this.deliverystatus;
	}

	public void setDeliverystatus(String deliverystatus) {
		this.deliverystatus = deliverystatus;
	}

	@Column(name = "divisionname", length = 225)
	public String getDivisionname() {
		return this.divisionname;
	}

	public void setDivisionname(String divisionname) {
		this.divisionname = divisionname;
	}

	@Column(name = "regionname", length = 225)
	public String getRegionname() {
		return this.regionname;
	}

	public void setRegionname(String regionname) {
		this.regionname = regionname;
	}

	@Column(name = "circlename", length = 225)
	public String getCirclename() {
		return this.circlename;
	}

	public void setCirclename(String circlename) {
		this.circlename = circlename;
	}

	@Column(name = "taluk", length = 225)
	public String getTaluk() {
		return this.taluk;
	}

	public void setTaluk(String taluk) {
		this.taluk = taluk;
	}

	@Column(name = "districtname", length = 225)
	public String getDistrictname() {
		return this.districtname;
	}

	public void setDistrictname(String districtname) {
		this.districtname = districtname;
	}

	@Column(name = "statename", length = 225)
	public String getStatename() {
		return this.statename;
	}

	public void setStatename(String statename) {
		this.statename = statename;
	}

}
