package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "services", catalog = "services", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Services implements java.io.Serializable {

	private Integer serviceId;
	private String companyLocation;
	private String companyName;
	private Date createDate;
	private String name;
	private String personInCharge;
	private String personInChargeDivision;
	private String personInChargeEmail;
	private String personInChargePhonenumber;
	private String countryId;
	private Integer stateId;
	private Integer cityId;
	private String area;
	private String pincode;
	private String contactNo2;
	private String contactNo3;
	private Integer isActive;
	private Set<UserServiceMapping> userServiceMappings = new HashSet<UserServiceMapping>(
			0);
	private Set<ServiceImageMapping> serviceImageMappings = new HashSet<ServiceImageMapping>(
			0);
	private Set<ServiceCategoryMapping> serviceCategoryMappings = new HashSet<ServiceCategoryMapping>(
			0);
	private MyServcie myServcie;

	public Services() {
	}

	public Services(Date createDate, String name, String countryId) {
		this.createDate = createDate;
		this.name = name;
		this.countryId = countryId;
	}

	public Services(String companyLocation, String companyName,
			Date createDate, String name, String personInCharge,
			String personInChargeDivision, String personInChargeEmail,
			String personInChargePhonenumber, String countryId,
			Integer stateId, Integer cityId, String area, String pincode,
			String contactNo2, String contactNo3, Integer isActive,
			Set<UserServiceMapping> userServiceMappings,
			Set<ServiceImageMapping> serviceImageMappings,
			Set<ServiceCategoryMapping> serviceCategoryMappings,
			MyServcie myServcie) {
		this.companyLocation = companyLocation;
		this.companyName = companyName;
		this.createDate = createDate;
		this.name = name;
		this.personInCharge = personInCharge;
		this.personInChargeDivision = personInChargeDivision;
		this.personInChargeEmail = personInChargeEmail;
		this.personInChargePhonenumber = personInChargePhonenumber;
		this.countryId = countryId;
		this.stateId = stateId;
		this.cityId = cityId;
		this.area = area;
		this.pincode = pincode;
		this.contactNo2 = contactNo2;
		this.contactNo3 = contactNo3;
		this.isActive = isActive;
		this.userServiceMappings = userServiceMappings;
		this.serviceImageMappings = serviceImageMappings;
		this.serviceCategoryMappings = serviceCategoryMappings;
		this.myServcie = myServcie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "serviceID", unique = true, nullable = false)
	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "companyLocation")
	public String getCompanyLocation() {
		return this.companyLocation;
	}

	public void setCompanyLocation(String companyLocation) {
		this.companyLocation = companyLocation;
	}

	@Column(name = "companyName")
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createDate", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "personInCharge")
	public String getPersonInCharge() {
		return this.personInCharge;
	}

	public void setPersonInCharge(String personInCharge) {
		this.personInCharge = personInCharge;
	}

	@Column(name = "personInChargeDivision")
	public String getPersonInChargeDivision() {
		return this.personInChargeDivision;
	}

	public void setPersonInChargeDivision(String personInChargeDivision) {
		this.personInChargeDivision = personInChargeDivision;
	}

	@Column(name = "personInChargeEmail")
	public String getPersonInChargeEmail() {
		return this.personInChargeEmail;
	}

	public void setPersonInChargeEmail(String personInChargeEmail) {
		this.personInChargeEmail = personInChargeEmail;
	}

	@Column(name = "personInChargePhonenumber")
	public String getPersonInChargePhonenumber() {
		return this.personInChargePhonenumber;
	}

	public void setPersonInChargePhonenumber(String personInChargePhonenumber) {
		this.personInChargePhonenumber = personInChargePhonenumber;
	}

	@Column(name = "countryID", nullable = false)
	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Column(name = "stateID")
	public Integer getStateId() {
		return this.stateId;
	}

	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	@Column(name = "cityID")
	public Integer getCityId() {
		return this.cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@Column(name = "area")
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "pincode", length = 10)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "contactNo2", length = 15)
	public String getContactNo2() {
		return this.contactNo2;
	}

	public void setContactNo2(String contactNo2) {
		this.contactNo2 = contactNo2;
	}

	@Column(name = "contactNo3", length = 15)
	public String getContactNo3() {
		return this.contactNo3;
	}

	public void setContactNo3(String contactNo3) {
		this.contactNo3 = contactNo3;
	}

	@Column(name = "isActive")
	public Integer getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Integer isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<UserServiceMapping> getUserServiceMappings() {
		return this.userServiceMappings;
	}

	public void setUserServiceMappings(
			Set<UserServiceMapping> userServiceMappings) {
		this.userServiceMappings = userServiceMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<ServiceImageMapping> getServiceImageMappings() {
		return this.serviceImageMappings;
	}

	public void setServiceImageMappings(
			Set<ServiceImageMapping> serviceImageMappings) {
		this.serviceImageMappings = serviceImageMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "services")
	public Set<ServiceCategoryMapping> getServiceCategoryMappings() {
		return this.serviceCategoryMappings;
	}

	public void setServiceCategoryMappings(
			Set<ServiceCategoryMapping> serviceCategoryMappings) {
		this.serviceCategoryMappings = serviceCategoryMappings;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "services")
	public MyServcie getMyServcie() {
		return this.myServcie;
	}

	public void setMyServcie(MyServcie myServcie) {
		this.myServcie = myServcie;
	}

}
