package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServiceImageMapping generated by hbm2java
 */
@Entity
@Table(name = "service_image_mapping", catalog = "services")
public class ServiceImageMapping implements java.io.Serializable {

	private ServiceImageMappingId id;
	private Services services;

	public ServiceImageMapping() {
	}

	public ServiceImageMapping(ServiceImageMappingId id, Services services) {
		this.id = id;
		this.services = services;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "imageId", column = @Column(name = "image_id", nullable = false)),
			@AttributeOverride(name = "imageOrder", column = @Column(name = "image_order", nullable = false)),
			@AttributeOverride(name = "serviceId", column = @Column(name = "service_id", nullable = false)),
			@AttributeOverride(name = "imageUrl", column = @Column(name = "imageURL", nullable = false)) })
	public ServiceImageMappingId getId() {
		return this.id;
	}

	public void setId(ServiceImageMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_id", nullable = false, insertable = false, updatable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

}
