package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ServiceCategoryMapping generated by hbm2java
 */
@Entity
@Table(name = "service_category_mapping", catalog = "services")
public class ServiceCategoryMapping implements java.io.Serializable {

	private ServiceCategoryMappingId id;
	private Services services;
	private ServiceCategory serviceCategory;

	public ServiceCategoryMapping() {
	}

	public ServiceCategoryMapping(ServiceCategoryMappingId id) {
		this.id = id;
	}

	public ServiceCategoryMapping(ServiceCategoryMappingId id,
			Services services, ServiceCategory serviceCategory) {
		this.id = id;
		this.services = services;
		this.serviceCategory = serviceCategory;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "categoryId", column = @Column(name = "categoryID")),
			@AttributeOverride(name = "serviceId", column = @Column(name = "serviceID")) })
	public ServiceCategoryMappingId getId() {
		return this.id;
	}

	public void setId(ServiceCategoryMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "serviceID", insertable = false, updatable = false)
	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoryID", insertable = false, updatable = false)
	public ServiceCategory getServiceCategory() {
		return this.serviceCategory;
	}

	public void setServiceCategory(ServiceCategory serviceCategory) {
		this.serviceCategory = serviceCategory;
	}

}
