package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServiceImageMappingId generated by hbm2java
 */
@Embeddable
public class ServiceImageMappingId implements java.io.Serializable {

	private int imageId;
	private int imageOrder;
	private int serviceId;
	private String imageUrl;

	public ServiceImageMappingId() {
	}

	public ServiceImageMappingId(int imageId, int imageOrder, int serviceId,
			String imageUrl) {
		this.imageId = imageId;
		this.imageOrder = imageOrder;
		this.serviceId = serviceId;
		this.imageUrl = imageUrl;
	}

	@Column(name = "image_id", nullable = false)
	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}

	@Column(name = "image_order", nullable = false)
	public int getImageOrder() {
		return this.imageOrder;
	}

	public void setImageOrder(int imageOrder) {
		this.imageOrder = imageOrder;
	}

	@Column(name = "service_id", nullable = false)
	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "imageURL", nullable = false)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServiceImageMappingId))
			return false;
		ServiceImageMappingId castOther = (ServiceImageMappingId) other;

		return (this.getImageId() == castOther.getImageId())
				&& (this.getImageOrder() == castOther.getImageOrder())
				&& (this.getServiceId() == castOther.getServiceId())
				&& ((this.getImageUrl() == castOther.getImageUrl()) || (this
						.getImageUrl() != null
						&& castOther.getImageUrl() != null && this
						.getImageUrl().equals(castOther.getImageUrl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getImageId();
		result = 37 * result + this.getImageOrder();
		result = 37 * result + this.getServiceId();
		result = 37 * result
				+ (getImageUrl() == null ? 0 : this.getImageUrl().hashCode());
		return result;
	}

}
