package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserServiceMappingId generated by hbm2java
 */
@Embeddable
public class UserServiceMappingId implements java.io.Serializable {

	private int roleId;
	private int serviceId;
	private int userId;

	public UserServiceMappingId() {
	}

	public UserServiceMappingId(int roleId, int serviceId, int userId) {
		this.roleId = roleId;
		this.serviceId = serviceId;
		this.userId = userId;
	}

	@Column(name = "roleID", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "serviceID", nullable = false)
	public int getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserServiceMappingId))
			return false;
		UserServiceMappingId castOther = (UserServiceMappingId) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& (this.getServiceId() == castOther.getServiceId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getServiceId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
