package com.services.cloud.model;

// Generated Jan 4, 2016 5:30:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserRoles generated by hbm2java
 */
@Entity

@Table(name = "user_roles", catalog = "services", uniqueConstraints = @UniqueConstraint(columnNames = "role"))
public class UserRoles implements java.io.Serializable {

	private Integer roleId;
	private String role;
	private Set<UserServiceMapping> userServiceMappings = new HashSet<UserServiceMapping>(
			0);
	private Set<UserRoleMapping> userRoleMappings = new HashSet<UserRoleMapping>(
			0);

	public UserRoles() {
	}

	public UserRoles(String role) {
		this.role = role;
	}

	public UserRoles(String role, Set<UserServiceMapping> userServiceMappings,
			Set<UserRoleMapping> userRoleMappings) {
		this.role = role;
		this.userServiceMappings = userServiceMappings;
		this.userRoleMappings = userRoleMappings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "roleID", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role", unique = true, nullable = false, length = 50)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoles")
	public Set<UserServiceMapping> getUserServiceMappings() {
		return this.userServiceMappings;
	}

	public void setUserServiceMappings(
			Set<UserServiceMapping> userServiceMappings) {
		this.userServiceMappings = userServiceMappings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRoles")
	public Set<UserRoleMapping> getUserRoleMappings() {
		return this.userRoleMappings;
	}

	public void setUserRoleMappings(Set<UserRoleMapping> userRoleMappings) {
		this.userRoleMappings = userRoleMappings;
	}

}
